name: Question/Query
description: Use this template to file a question/query for the team that are not bugs or feature requests.
title: "[QUERY]"

body:
  - type: input
    id: version
    attributes:
      label: Release version
      description: Name and version of the release package used
      placeholder: e.g. AzMigExport v2.0.02252.59
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Query/Question
      description: How can we help?
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide more information on your environment:
          * Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Windows 10 .NET Framework 4.8]
          * IDE and version (if during development) : [e.g. Visual Studio 16.3]
      placeholder: Environment
    validations:
      required: false
